config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users
  resources :products
  resources :orders, only: [:index, :show, :create, :destroy]
  
  root 'simple_pages#landing_page'

  get 'simple_pages/about'

  get 'simple_pages/contact'

  get 'simple_pages/index'

  

  post 'simple_pages/thank_you'


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord

  def self.search(search_term)
    Product.where("name LIKE ?", "%#{search_term}%")
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders #may need to remove this line not shown in example 5.4
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end

  def thank_you
    @name = params[:name]
  	@email = params[:email]
  	@message = params[:message]
  	UserMailer.contact_form(@email, @name, @message).deliver_now
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def destroy
  end

  before_action :authenticate_user!
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      #return our filtered list here
      @products = Product.search(search_term)
    else
      #@products = Product.limit(5)
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        #format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.html { redirect_to "/simple_pages/landing_page", notice: 'Product was successfully updated'}
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price)
    end
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
  end

  def landing_page
  	@featured_product = Product.first
  	@products = Product.limit(5)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :Last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Bike Berlin", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", 'simple_pages/index'%></li>
        <li><%= link_to "About", 'about'%></li>
        <li><%= link_to "Contact", 'contact'%></li>
        <li><%= form_with(url: products_path, method: 'get', local: true) do |form| %>
    <%= form.label :q, 'Search for:' %>
    <%= form.text_field :q, id: 'q', value: params[:q] %>
    <%= form.submit 'Search' %>
    <% end %></li>
      </ul>
      <ul class="nav pull-right">
        <div id="login">
          <li>
            <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
            <% else %>
              <%= link_to('Login', new_user_session_path) %>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BikeApp</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  <%= render 'layouts/header' %>

  <%= yield %>

  <footer>
    &copy; 2017 Bike Berlin
  </footer>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :product_image_url %>
  </div>

  <div class="field">
    <%= form.label :color %><br>
    <%= form.text_field :color %>
  </div>

  <div class="field">
    <%= form.label :price %><br>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="col-sm-2 col-md-4">
        <%= image_tag(product.image_url, class: "img-responsive") %>
          <a href="#"><h1><%= product.name %></h1></a>
          <p><%= product.description %></p>
          <strong><%= product.price %></strong>
      </div><!-- /col -->

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1 id="product-page-head">Products</h1>

<div class="container-fluid">
  <div class="row">
  <%# @products.each do |product| %>
    <%= render @products %>
  <%# end %>
  </div>
</div>
  

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Color:</strong>
  <%= @product.color %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/simple_pages/about.html.erb
<h1>About Us</h1>
<p>This will be a demo app for a bike shop</p>

app/views/simple_pages/contact.html.erb
<h1>Contact</h1>

<h1>Contact Us</h1>

<%= flash[:notice] %>

<%= form_with(url: "/simple_pages/thank_you") do |form| %>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control", placeholder: "Enter Name" %>
      </div>        
      <div class="form-group">
        <%= form.label :email, "Email Address" %>
        <%= form.text_field :email, class: "form-control", placeholder: "Enter Email" %>
      </div>
      <div class="form-group">
        <%= form.label :message %>
        <%= form.text_area :message, class: "form-control", placeholder: "Enter Message" %>
      </div>        
    </div>
  </div>
  <%= form.submit "Send" %>   
<% end %>

<div>
  <p>Bike Shop Berlin</p><br>
  <p>Berlin, Germany</p><br>
  <P>P: +49 56 78 34 00 02</P><br>
  <p>E: shop@bikeberlin.com</p><br>
</div>

app/views/simple_pages/index.html.erb
<p>Welcome! The date and time is <%= Time.now %></p>
<%= image_tag("main_page_bikes.jpg", class: "img-responsive") %>

app/views/simple_pages/landing_page.html.erb
<%= params[:example_key].to_i * 10 %>
<h2>Featured Product:</h2>
<%= @featured_product.name %>


<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% @products.each do |product| %>
      <div class="item<%= "active" if product == @products.first %>">
        <%= image_tag(product.image_url, :class => "img_preview") %>
        <div class="carousel-caption">
          <%= product.name %>
        </div>
      </div>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/simple_pages/thank_you.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <p>Thank you. We have received your message and will respond as soon as possible.</p>
  </div><!-- / panel-body -->
</div><!-- / panel -->

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :user_first_name %>
  </div>

  <div class="field">
    <%= form.label :Last_name %>
    <%= form.text_field :Last_name, id: :user_Last_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.Last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.Last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>